---
title: "CV"
author: "`r full_name`"
email: mpschramm@gmail.com
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
geometry: margin=1in
github: mps9506
fontawesome: yes
phone: 910 232-3760
address: 578 John Kimbrough Blvd · 2260 TAMU · College Station, TX 77843
updated: no
bibliography_peer_review: "`r peer_review_path`"
bibliography_tech_report: "`r tech_report_path`"
bibliography_conference: "`r conf_path`"
bibliography_software: "`r soft_path`"
bibliography_datasets: "`r data_path`"
nocite: '@*'
csl: "`r csl_loc`"
---
```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

```

## Research Experience

```{r}
cv_data %>% CVR::print_section('research_positions',
                               glue_template = "
{timeline} \\hfill {institution} \\newline {title} \\hfill {loc} \\newline \\newline
")
```

## Education
```{r}
cv_data %>% CVR::print_section('education',
                               glue_template = "
{timeline} \\hfill {institution} \\newline {title} \\hfill {loc} \\newline \\newline
")
```

## Research Area
```{r}
cv_data %>% CVR::print_text_block('research')
```

## Skills
```{r}
cv_data %>% CVR::print_text_block('skills')
```

## Peer Reviewed Articles

::: {#refs_peer_review}
:::


## Technical Reports
::: {#refs_tech_report}
:::

## Presentations
::: {#refs_conference}
:::

## Published Software
::: {#refs_software}
:::

## Published Datasets
::: {#refs_datasets}
:::


## Grants and Projects
```{r}
cv_data %>% CVR::print_section('grant_project',
                           glue_template = "
{timeline} *{institution}*: {title}. Amount: {loc}. \\newline \\newline
")
```

## Awards and Honors

```{r}
cv_data %>% CVR::print_section('awards',
                           glue_template = "
{title} \n\n
")
```

## Service

### Review committees
```{r}
cv_data %>% CVR::print_section('committee',
                           glue_template = "
{timeline}: {title} \n
# ")
```

### Peer review
```{r}
cv_data %>% CVR::print_section('j_peer_review',
                           glue_template = "
*{title}* \n
")
```

